[tool.poetry]
name = "poetry-tips"
version = "0.4.0"
description = ""
authors = ["aliseylaneh@gmail.com"]
[tool.poetry.dependencies]
python = "^3.10.12"
pika = "^1.3.2"
httpx = "^0.27.0"
tqdm = "^4.66.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
