version: '2.27.0'

services:

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch_lab
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_JAVA_OPTS = "-Xmx256m -Xms256m"
      - discovery.type=single-node
      - xpack.security.enabled= false
      - xpack.security.enrollment.enabled= false

  logstash:
    image: logstash:8.13.0
    container_name: logstash_lab
    restart: always
    volumes:
      - logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

volumes:
  elastic-data:
